using System;

namespace Hopper.Core.Components
{
    /// <summary>
    /// Enables autogeneration of various shortcuts for acessing methods of the
    /// behavior through the entity. They are added as extension methods over entities.
    /// The parameter passed down the constructor indicates the name of those methods.
    /// The resulting code depends on the chains that the behavior adds.
    /// </summary>
    /// <example>
    /// Applying the attribute with alias "Attack" and chains "Do" and "Check"
    /// will create the following extension methods:
    /// Act(), TryAct()                            methods call the activation
    /// UnconditionalAct(), TryUnconditionalAct()  call the Do() method
    /// CheckAct(), TryCheckAct()                  methods call the Check() method 
    /// </example>
    public class AliasAttribute : Attribute
    {
        public AliasAttribute(string alias)
        {
        }
    }

    /// <summary>
    /// Enables autogeneration of chain related fields and methods of the behavior.
    /// Important: you must define the Context type that will be passed down 
    /// the chain in the scope of your behavior class. The autogenerated chains
    /// will work off of this Context type. 
    /// </summary>
    /// <example>
    /// Say, the selected chains are "Check" and "Do". 
    /// Fields for the chain objects will be autogenerated.
    /// The generated code will contain methods Check() and Do(),
    /// which contruct the context by filling in 
    /// the individual fields and calls the other method pair.
    /// The other pair is TraverseCheck() and TraverseDo() which traverse 
    /// the chain with the given context and returns context.success by default.
    /// If a custom overload for one of the signatures has been provided, 
    /// the corresponing overload will not be autogenerated.
    /// </example>
    public class ChainsAttribute : Attribute
    {
        public ChainsAttribute(params string[] chains)
        {
        }
    }

    /// <summary>
    /// Indicates the required fields that must be filled in on initialization 
    /// of the given Behavior. *Some init method stuff, don't know yet*
    /// </summary>
    public class InjectAttribute : Attribute {}

    /// <summary>
    /// Enables autogeneration of a field of the given type and helper methods for the given enum.
    /// The methods and the fields are generated in the given scope.
    /// If the scope is a namespace, no field will be generated. The generated code would
    /// contain just extensions methods for the enum type, in a static class.
    /// If the scope is a class, same methods will be generated in a static class in the scope of the
    /// parent class, but in addition a field of that enum type and methods for querying that field
    /// will also appear in the generated code.
    /// E.g. an enum with members `Nice` and `Cool` 
    /// in an enum named Hello will generate the following methods:
    /// if in a namespace or a class scope:   IsNice(this Hello), IsCool(this Hello),
    ///             Hello SetNice(this Hello, bool), Hello SetCool(this Hello, bool);
    /// if in a class scope:                  Hello _hello, IsNice(), IsCool(), ClearHello(),
    ///                                       SetNice(bool), SetCool(bool).
    /// </summary>
    public class FlagsAttribute : Attribute {}


    /// <summary>
    /// Enables automatic generation of the Activate() method.
    /// By default, it would construct the Context, traverse the Check chain, check if 
    /// the check chain succeeded and the traverse the Do chain.
    /// Returns true if the check succeeds.
    /// </summary>
    public class AutoActivationAttribute : Attribute 
    {
        public AutoActivationAttribute(string alias)
        {
        }
    }

}